import { App, Notice, PluginSettingTab, Setting, setIcon } from 'obsidian';
import type TypographyPlugin from './main';
import type { FontSize } from './renderer';
import { createProvider, ModelProviderProfile, ProviderPreset, PROVIDER_PRESETS } from './model-config';

export interface TypographySettings {
  theme:string;fontSize:FontSize;backgroundType:'none'|'default'|'grid';fontWeight:'light'|'regular'|'bold';headingStyle:'numbers'|'eyes'|'none';codeTheme:'github-light'|'github-dark';includeReadingTime:boolean;avatarUrl:string;
  providers:ModelProviderProfile[];activeTextProviderId:string;activeImageProviderId:string;imageSize:string;imageFolder:string;
  wechatAppId:string;wechatSecret:string;wechatProxyUrl:string;author:string;defaultCover:string;
}

const initial=createProvider('openai');
export const DEFAULT_SETTINGS:TypographySettings={theme:'default',fontSize:'medium',backgroundType:'none',fontWeight:'regular',headingStyle:'numbers',codeTheme:'github-dark',includeReadingTime:false,avatarUrl:'',providers:[initial],activeTextProviderId:initial.id,activeImageProviderId:initial.id,imageSize:'1536x1024',imageFolder:'assets/typography',wechatAppId:'',wechatSecret:'',wechatProxyUrl:'',author:'',defaultCover:''};

export class TypographySettingTab extends PluginSettingTab{
  plugin:TypographyPlugin;private addingPreset:ProviderPreset='openai';private selectedProviderId='';
  constructor(app:App,plugin:TypographyPlugin){super(app,plugin);this.plugin=plugin;}
  display():void{
    const el=this.containerEl,scrollState=this.captureScrollState();el.empty();el.addClass('typography-settings');
    this.providers(el);this.appearance(el);this.publishing(el);
    this.restoreScrollState(scrollState);
  }
  private captureScrollState(){const state:Array<{element:HTMLElement;top:number;left:number}>=[];let current:HTMLElement|null=this.containerEl;while(current){state.push({element:current,top:current.scrollTop,left:current.scrollLeft});current=current.parentElement;}const scrolling=document.scrollingElement as HTMLElement|null;if(scrolling&&!state.some(item=>item.element===scrolling))state.push({element:scrolling,top:scrolling.scrollTop,left:scrolling.scrollLeft});return state;}
  private restoreScrollState(state:Array<{element:HTMLElement;top:number;left:number}>){const restore=()=>state.forEach(item=>{item.element.scrollTop=item.top;item.element.scrollLeft=item.left;});restore();window.requestAnimationFrame(()=>{restore();window.requestAnimationFrame(restore);});window.setTimeout(restore,0);window.setTimeout(restore,60);window.setTimeout(restore,180);}
  private section(el:HTMLElement,icon:string,title:string,desc:string){const header=el.createDiv({cls:'typography-section-heading'});setIcon(header.createSpan(),icon);const copy=header.createDiv();copy.createEl('h3',{text:title});copy.createEl('p',{text:desc});}
  private providers(el:HTMLElement){
    this.section(el,'network','模型提供商','管理不同模型服务的接口协议、模型、密钥、能力与连接状态。');
    const addRow=el.createDiv({cls:'typography-provider-add'});const select=addRow.createEl('select');(Object.keys(PROVIDER_PRESETS) as ProviderPreset[]).forEach(id=>select.createEl('option',{text:PROVIDER_PRESETS[id].name,value:id}));select.value=this.addingPreset;select.onchange=()=>this.addingPreset=select.value as ProviderPreset;
    const scan=addRow.createEl('button',{text:'检测本机配置'});setIcon(scan.createSpan({cls:'typography-button-icon'}),'scan-search');scan.onclick=async()=>{scan.disabled=true;await this.plugin.scanLocalModelConfigs(true);const detected=this.plugin.settings.providers.find(p=>p.configSource==='claude'&&this.plugin.isProviderConfigured(p))||this.plugin.settings.providers.find(p=>p.configSource==='codex'&&this.plugin.isProviderConfigured(p))||this.plugin.settings.providers.find(p=>p.configSource==='claude'||p.configSource==='codex');if(detected)this.selectedProviderId=detected.id;this.display();};
    const add=addRow.createEl('button',{text:'添加提供商',cls:'mod-cta'});setIcon(add.createSpan({cls:'typography-button-icon'}),'plus');add.onclick=async()=>{const p=createProvider(this.addingPreset,this.plugin.settings.providers.length);this.plugin.settings.providers.push(p);this.selectedProviderId=p.id;if(!this.plugin.settings.activeTextProviderId&&p.textEnabled)this.plugin.settings.activeTextProviderId=p.id;if(!this.plugin.settings.activeImageProviderId&&p.imageEnabled)this.plugin.settings.activeImageProviderId=p.id;await this.plugin.saveSettings();this.display();};
    const workspace=el.createDiv({cls:'typography-provider-workspace'});
    if(!this.plugin.settings.providers.length){const empty=workspace.createDiv({cls:'typography-provider-empty'});setIcon(empty.createDiv(),'unplug');empty.createEl('strong',{text:'尚未配置模型提供商'});empty.createEl('span',{text:'添加一个预设后即可开始配置。'});}else{
      if(!this.plugin.settings.providers.some(p=>p.id===this.selectedProviderId))this.selectedProviderId=this.plugin.settings.providers[0].id;
      const switcher=workspace.createDiv({cls:'typography-provider-switcher'});
      for(const item of this.plugin.settings.providers){const button=switcher.createEl('button',{cls:`typography-provider-tab${item.id===this.selectedProviderId?' is-active':''}`});setIcon(button.createSpan(),item.protocol==='anthropic'?'sparkles':item.protocol==='codex-runtime'?'terminal-square':'boxes');const label=button.createSpan();label.createEl('strong',{text:item.name});label.createEl('small',{text:this.statusLabel(item.connection.status)});button.onclick=()=>{this.selectedProviderId=item.id;this.display();};}
      const editor=workspace.createDiv({cls:'typography-provider-editor'});const selected=this.plugin.settings.providers.find(p=>p.id===this.selectedProviderId);if(selected)this.card(editor,selected);
    }
    const route=el.createDiv({cls:'typography-routing-panel'});const rt=route.createDiv({cls:'typography-routing-title'});setIcon(rt.createSpan(),'route');rt.createEl('strong',{text:'任务路由'});
    new Setting(route).setName('文本任务提供商').setDesc('写作、标题生成与自然化处理').addDropdown(d=>{const rows=this.plugin.settings.providers.filter(p=>p.textEnabled);if(!rows.length)d.addOption('','无可用提供商');else rows.forEach(p=>d.addOption(p.id,p.name));d.setValue(this.plugin.settings.activeTextProviderId).onChange(async v=>{this.plugin.settings.activeTextProviderId=v;await this.plugin.saveSettings();this.display();});});
    new Setting(route).setName('图片任务提供商').setDesc('封面与信息图生成').addDropdown(d=>{const rows=this.plugin.settings.providers.filter(p=>p.imageEnabled);if(!rows.length)d.addOption('','无可用提供商');else rows.forEach(p=>d.addOption(p.id,p.name));d.setValue(this.plugin.settings.activeImageProviderId).onChange(async v=>{this.plugin.settings.activeImageProviderId=v;await this.plugin.saveSettings();this.display();});});
  }
  private card(parent:HTMLElement,p:ModelProviderProfile){
    const card=parent.createDiv({cls:'typography-provider-card'});card.dataset.status=p.connection.status;const top=card.createDiv({cls:'typography-provider-card-top'});const identity=top.createDiv({cls:'typography-provider-identity'});setIcon(identity.createDiv({cls:'typography-provider-mark'}),p.protocol==='anthropic'?'sparkles':p.protocol==='codex-runtime'?'terminal-square':'boxes');const names=identity.createDiv();names.createEl('strong',{text:p.name});names.createEl('span',{text:p.protocol==='anthropic'?'Anthropic Messages':p.protocol==='codex-runtime'?'Codex 登录会话':'OpenAI-compatible'});const status=top.createDiv({cls:`typography-status typography-status-${p.connection.status}`});setIcon(status.createSpan(),this.statusIcon(p.connection.status));status.createSpan({text:this.statusLabel(p.connection.status)});
    const badges=card.createDiv({cls:'typography-provider-badges'});if(p.configSource==='claude')this.badge(badges,'scan-search','自动检测 · Claude');if(p.configSource==='codex')this.badge(badges,'scan-search','自动检测 · Codex');if(this.plugin.settings.activeTextProviderId===p.id)this.badge(badges,'file-text','文本路由');if(this.plugin.settings.activeImageProviderId===p.id)this.badge(badges,'image','图片路由');if(p.connection.latencyMs!==undefined)this.badge(badges,'activity',`${p.connection.latencyMs} ms`);
    new Setting(card).setName('显示名称').addText(t=>t.setValue(p.name).onChange(v=>this.update(p,'name',v)));
    new Setting(card).setName('接口协议').addDropdown(d=>d.addOption('openai-compatible','OpenAI-compatible').addOption('anthropic','Anthropic Messages').addOption('codex-runtime','Codex 登录会话').setValue(p.protocol).onChange(v=>this.update(p,'protocol',v)));
    if(p.protocol!=='codex-runtime')new Setting(card).setName('Base URL').setDesc('远程服务应使用 HTTPS').addText(t=>t.setPlaceholder('https://api.example.com/v1').setValue(p.baseUrl).onChange(v=>this.update(p,'baseUrl',v.trim().replace(/\/+$/,''))));
    if(p.protocol!=='codex-runtime')this.secretEditor(card,p);else new Setting(card).setName('认证来源').setDesc('自动复用本机 Codex 的登录状态，不需要再次填写 API Key').addButton(b=>b.setButtonText('已自动接入').setDisabled(true));
    new Setting(card).setName('文本能力').addToggle(t=>t.setValue(p.textEnabled).onChange(async v=>{p.textEnabled=v;if(!v&&this.plugin.settings.activeTextProviderId===p.id)this.plugin.settings.activeTextProviderId=this.plugin.settings.providers.find(x=>x.id!==p.id&&x.textEnabled)?.id||'';await this.plugin.saveSettings();this.display();}));
    if(p.textEnabled){new Setting(card).setName('文本模型').setDesc('支持手动输入任意兼容模型 ID').addText(t=>t.setPlaceholder('model-id').setValue(p.textModel).onChange(v=>this.update(p,'textModel',v.trim())));if(p.discoveredModels.length)new Setting(card).setName('从模型目录选择').addDropdown(d=>{d.addOption('','选择模型');p.discoveredModels.forEach(id=>d.addOption(id,id));d.setValue(p.discoveredModels.includes(p.textModel)?p.textModel:'').onChange(async v=>{if(v){p.textModel=v;await this.plugin.saveSettings();this.display();}});});}
    new Setting(card).setName('图片能力').setDesc(p.protocol==='codex-runtime'?'Codex 登录会话仅用于文本任务':'用于封面和信息图生成').addToggle(t=>t.setDisabled(p.protocol==='codex-runtime').setValue(p.protocol==='codex-runtime'?false:p.imageEnabled).onChange(async v=>{p.imageEnabled=v;if(!v&&this.plugin.settings.activeImageProviderId===p.id)this.plugin.settings.activeImageProviderId=this.plugin.settings.providers.find(x=>x.id!==p.id&&x.imageEnabled)?.id||'';await this.plugin.saveSettings();this.display();}));
    if(p.imageEnabled){new Setting(card).setName('图片模型').addText(t=>t.setPlaceholder('image-model-id').setValue(p.imageModel).onChange(v=>this.update(p,'imageModel',v.trim())));new Setting(card).setName('图片 Base URL').setDesc('留空时沿用主 Base URL').addText(t=>t.setPlaceholder(p.baseUrl).setValue(p.imageBaseUrl).onChange(v=>this.update(p,'imageBaseUrl',v.trim().replace(/\/+$/,''))));}
    const details=card.createEl('details',{cls:'typography-provider-advanced'});details.createEl('summary',{text:'高级参数'});const adv=details.createDiv();new Setting(adv).setName('认证方式').setDesc('Anthropic API Key 使用 x-api-key；Claude Auth Token 和 OpenAI 兼容服务通常使用 Bearer').addDropdown(d=>d.addOption('auto','自动').addOption('bearer','Authorization: Bearer').addOption('x-api-key','x-api-key').setValue(p.authMode||'auto').onChange(v=>this.update(p,'authMode',v)));new Setting(adv).setName('请求超时').setDesc('5–300 秒').addText(t=>{t.inputEl.type='number';t.setValue(String(Math.round(p.timeoutMs/1000))).onChange(v=>this.update(p,'timeoutMs',Math.min(300,Math.max(5,Number(v)||60))*1000));});new Setting(adv).setName('最大输出 Tokens').addText(t=>{t.inputEl.type='number';t.setValue(String(p.maxTokens)).onChange(v=>this.update(p,'maxTokens',Math.min(200000,Math.max(1,Number(v)||8192))));});new Setting(adv).setName('Temperature').setDesc('0–2').addText(t=>{t.inputEl.type='number';t.inputEl.step='0.1';t.setValue(String(p.temperature)).onChange(v=>this.update(p,'temperature',Math.min(2,Math.max(0,Number(v)||0))));});new Setting(adv).setName('自定义请求头').setDesc('JSON 对象，会覆盖默认请求头').addTextArea(t=>t.setPlaceholder('{\n  "X-Custom-Header": "value"\n}').setValue(p.customHeaders).onChange(v=>this.update(p,'customHeaders',v)));
    const diagnostic=card.createDiv({cls:'typography-diagnostic'});setIcon(diagnostic.createSpan(),p.connection.status==='error'?'circle-alert':'circle-check');const dt=diagnostic.createDiv();dt.createEl('span',{text:p.connection.message||'尚未测试'});if(p.connection.testedAt)dt.createEl('small',{text:new Date(p.connection.testedAt).toLocaleString()});
    const actions=card.createDiv({cls:'typography-provider-actions'});const test=actions.createEl('button',{text:'测试连接',cls:'mod-cta'});setIcon(test.createSpan({cls:'typography-button-icon'}),'plug-zap');test.onclick=async()=>{test.disabled=true;try{await this.plugin.testProvider(p.id);}catch{}finally{this.display();}};const refresh=actions.createEl('button',{text:'刷新模型'});setIcon(refresh.createSpan({cls:'typography-button-icon'}),'refresh-cw');refresh.onclick=async()=>{refresh.disabled=true;try{await this.plugin.refreshProviderModels(p.id);new Notice(`已刷新 ${p.name} 的模型目录`);}catch(e:any){new Notice(e.message,8000);}finally{this.display();}};const remove=actions.createEl('button',{text:'删除',cls:'typography-danger-button'});setIcon(remove.createSpan({cls:'typography-button-icon'}),'trash-2');remove.onclick=async()=>{remove.disabled=true;const currentIndex=this.plugin.settings.providers.findIndex(item=>item.id===p.id);try{await this.plugin.removeProvider(p.id);const remaining=this.plugin.settings.providers;this.selectedProviderId=remaining[Math.min(Math.max(0,currentIndex),remaining.length-1)]?.id||'';new Notice(`${p.name} 已删除`);}catch(e:any){new Notice(`删除失败：${e.message}`,8000);}finally{this.display();}};
  }
  private appearance(el:HTMLElement){this.section(el,'palette','排版外观','设置公众号内容的字重、标题、代码与阅读信息。');const panel=el.createDiv({cls:'typography-settings-panel'});new Setting(panel).setName('正文字重').addDropdown(d=>d.addOption('light','细').addOption('regular','中').addOption('bold','粗').setValue(this.plugin.settings.fontWeight).onChange(v=>this.save('fontWeight',v)));new Setting(panel).setName('小标题风格').addDropdown(d=>d.addOption('numbers','数字进度').addOption('eyes','眼睛进度').addOption('none','无标记').setValue(this.plugin.settings.headingStyle).onChange(v=>this.save('headingStyle',v)));new Setting(panel).setName('代码主题').addDropdown(d=>d.addOption('github-dark','GitHub Dark').addOption('github-light','GitHub Light').setValue(this.plugin.settings.codeTheme).onChange(v=>this.save('codeTheme',v)));new Setting(panel).setName('顶部阅读时间模块').addToggle(t=>t.setValue(this.plugin.settings.includeReadingTime).onChange(v=>this.save('includeReadingTime',v)));new Setting(panel).setName('作者头像 URL').addText(t=>t.setValue(this.plugin.settings.avatarUrl).onChange(v=>this.save('avatarUrl',v)));new Setting(panel).setName('图片尺寸').addText(t=>t.setValue(this.plugin.settings.imageSize).onChange(v=>this.save('imageSize',v)));new Setting(panel).setName('图片保存目录').addText(t=>t.setValue(this.plugin.settings.imageFolder).onChange(v=>this.save('imageFolder',v)));}
  private publishing(el:HTMLElement){this.section(el,'send','微信公众号草稿','发布凭证独立于模型配置；留空只会禁用微信发布。');const panel=el.createDiv({cls:'typography-settings-panel'});new Setting(panel).setName('WeChat AppID').addText(t=>t.setValue(this.plugin.settings.wechatAppId).onChange(v=>this.save('wechatAppId',v)));new Setting(panel).setName('WeChat AppSecret').addText(t=>{t.inputEl.type='password';return t.setValue(this.plugin.settings.wechatSecret).onChange(v=>this.save('wechatSecret',v));});new Setting(panel).setName('微信代理 URL（可选）').addText(t=>t.setValue(this.plugin.settings.wechatProxyUrl).onChange(v=>this.save('wechatProxyUrl',v)));new Setting(panel).setName('默认作者').addText(t=>t.setValue(this.plugin.settings.author).onChange(v=>this.save('author',v)));new Setting(panel).setName('默认封面路径').addText(t=>t.setValue(this.plugin.settings.defaultCover).onChange(v=>this.save('defaultCover',v)));}
  private badge(parent:HTMLElement,icon:string,text:string){const item=parent.createSpan({cls:'typography-route-badge'});setIcon(item.createSpan(),icon);item.createSpan({text});}
  private secretEditor(parent:HTMLElement,p:ModelProviderProfile){
    const saved=this.plugin.hasProviderSecret(p),box=parent.createDiv({cls:'typography-secret-editor'}),head=box.createDiv({cls:'typography-secret-head'});const title=head.createDiv();title.createEl('strong',{text:'API Key / Auth Token'});title.createEl('small',{text:saved?'已安全保存；输入新值可以替换':'尚未配置密钥'});const state=head.createSpan({cls:`typography-secret-state${saved?' is-saved':''}`});setIcon(state.createSpan(),saved?'shield-check':'shield-alert');state.createSpan({text:saved?'已保存':'未配置'});
    const row=box.createDiv({cls:'typography-secret-row'}),input=row.createEl('input',{type:'password',placeholder:saved?'已保存，输入新值进行替换':'输入 API Key 或 Auth Token',attr:{autocomplete:'off',spellcheck:'false'}}),reveal=row.createEl('button',{cls:'clickable-icon',attr:{type:'button','aria-label':'显示或隐藏密钥',title:'显示或隐藏密钥'}});setIcon(reveal,'eye');reveal.onclick=()=>{const visible=input.type==='text';input.type=visible?'password':'text';setIcon(reveal,visible?'eye':'eye-off');};
    const actions=box.createDiv({cls:'typography-secret-actions'}),save=actions.createEl('button',{text:'保存密钥',cls:'mod-cta'});setIcon(save.createSpan({cls:'typography-button-icon'}),'save');save.onclick=async()=>{const value=input.value.trim();if(!value){new Notice('请先输入 API Key 或 Auth Token');input.focus();return;}save.disabled=true;try{await this.plugin.setProviderSecret(p,value);if(!this.plugin.hasProviderSecret(p))throw new Error('写入 SecretStorage 后未能读取密钥');p.connection={status:'untested',message:'密钥已更新，等待测试连接'};await this.plugin.saveSettings();input.value='';new Notice(`${p.name} 的密钥已保存`);this.display();}catch(e:any){save.disabled=false;new Notice(`保存密钥失败：${e.message}`,8000);}};
    const clear=actions.createEl('button',{text:'清除密钥'});setIcon(clear.createSpan({cls:'typography-button-icon'}),'trash-2');clear.disabled=!saved;clear.onclick=async()=>{clear.disabled=true;try{await this.plugin.setProviderSecret(p,'');p.connection={status:'untested',message:'密钥已清除'};await this.plugin.saveSettings();new Notice(`${p.name} 的密钥已清除`);this.display();}catch(e:any){clear.disabled=false;new Notice(`清除密钥失败：${e.message}`,8000);}};
  }
  private statusIcon(s:string){return s==='connected'?'circle-check':s==='error'?'circle-x':s==='testing'?'loader-circle':'circle-dashed';}private statusLabel(s:string){return s==='connected'?'已连接':s==='error'?'异常':s==='testing'?'测试中':'未测试';}
  private async update(p:ModelProviderProfile,key:keyof ModelProviderProfile,value:any){(p as any)[key]=value;p.connection={status:'untested',message:'配置已修改，等待重新测试'};await this.plugin.saveSettings();}
  private async save(key:keyof TypographySettings,value:any){(this.plugin.settings as any)[key]=value;await this.plugin.saveSettings();}
}
